import os
import pandas as pd

# Generated by ~mkramer/projscratch/p17b/data_ana_lbnl/code/merge/make_dbd_runlist.py
# For post-P17B data, use gen_dbd_runlist.py
P17B_DRL_PATH = '../static/dbd_runlist/dbd_runlist_p17b.txt.gz'

class DailyRunList:
    def __init__(self):
        path = os.getenv("IBDSEL_DRL_PATH", default=P17B_DRL_PATH)
        self.df = pd.read_csv(path, sep=r'\s+', header=None,
                              names=['day', 'site', 'runno', 'fileno'])

    def daily(self, *, site, day):
        sub_df = self.df.query(f'site == {site} and day == {day}')
        return sub_df[['runno', 'fileno']].values
