import pandas as pd

# Generated by ~mkramer/projscratch/p17b/data_ana_lbnl/code/merge/make_dbd_runlist.py
# Need to write our own version that just uses the offline DB
DRL_PATH = '../static/dbd_runlist/dbd_runlist_p17b.txt.gz'

class DailyRunList:
    def __init__(self, path=DRL_PATH):
        self.df = pd.read_csv(path, sep='\t', header=None,
                              names=['day', 'site', 'runno', 'fileno'])

    def daily(self, *, site, day):
        sub_df = self.df.query(f'site == {site} and day == {day}')
        return sub_df[['runno', 'fileno']].values
